# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20160506_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='video',
            name='feautured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='free_preview',
            field=models.BooleanField(default=False),
        ),
    ]
