# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 05:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20160506_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoManager',
        ),
        migrations.AlterModelManagers(
            name='video',
            managers=[
                ('general_items', django.db.models.manager.Manager()),
            ],
        ),
    ]
