# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20160507_1043'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='video',
            managers=[
            ],
        ),
    ]
