# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_profileimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
