# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_delete_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='abc', unique=True),
        ),
    ]
