# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_video_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set([('slug', 'category')]),
        ),
    ]
