# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_video_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='amazon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
