# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0021_auto_20160623_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='product_embed',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
