# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_auto_20160807_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='product_embed',
            new_name='product_embed1',
        ),
        migrations.AddField(
            model_name='video',
            name='product_embed2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='product_embed3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='product_embed4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='product_embed5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='product_embed6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
