# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_auto_20160807_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='product_embed1',
            new_name='product_embed',
        ),
        migrations.RemoveField(
            model_name='video',
            name='product_embed2',
        ),
        migrations.RemoveField(
            model_name='video',
            name='product_embed3',
        ),
        migrations.RemoveField(
            model_name='video',
            name='product_embed4',
        ),
        migrations.RemoveField(
            model_name='video',
            name='product_embed5',
        ),
        migrations.RemoveField(
            model_name='video',
            name='product_embed6',
        ),
    ]
