"""
Django settings for vidos project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

print ("Base_Dir", BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '==vmw9obt6p(5)chezhrkb+(t9-h6%q219$58u-d*qbz9hi8*l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


ALLOWED_HOSTS = ['vidolee.herokuapp.com']

LOGIN_URL = "/login/"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'webmaster_verification',
    'social.apps.django_app.default',
    'videos',
    'myaccount',
    'django_filters',
    'braces',
    'widget_tweaks',
    'upload',
    
    
]




MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    #'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'vidos.urls'
WSGI_APPLICATION = 'vidos.wsgi.application'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],
        },
    },
]



#SOCIAL_AUTH_FACEBOOK_KEY='990787137707230'
#SOCIAL_AUTH_FACEBOOK_SECRET='7101253bd6d8359efbc731b2e8ef2ecd'
#SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = 'AIzaSyAFtKFhyCyOlsANUsOWDVouRoLt2hceTZY'
# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'd4dit1e500fis4',
        'USER': 'szbdhsiaoacqia',
        'PASSWORD': 'pNFcSKYOP7Aa_L5APmP2EzDmJr',
        'HOST': 'ec2-54-235-95-188.compute-1.amazonaws.com',
        'PORT': '5432',
        
        
    }
}

WEBMASTER_VERIFICATION = {
    #'bing': '<bing verification code>',
    'google': '<google490de29a933d2b95>',
    #'majestic': '<majestic verification code>',
    #'yandex': '<yandex verification code>',
    #'alexa': '<alexa verification code>',
}
# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static", "static_dirs"),
)

#print ("Static_Files", STATICFILES_DIRS)
STATIC_ROOT = os.path.join(BASE_DIR, "static", "static_root")

print ("Static_Root", STATIC_ROOT)

MEDIA_ROOT = os.path.join(BASE_DIR, "static", "media_root")
MEDIA_URL = '/media/'

print ("Media_Root", MEDIA_ROOT)
AUTHENTICATION_BACKENDS = (
        'social.backends.facebook.FacebookOAuth2',
        'social.backends.google.GoogleOAuth2',
        'social.backends.twitter.TwitterOAuth',
        'django.contrib.auth.backends.ModelBackend',
        
        
)