# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_auto_20160529_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_handle',
        ),
    ]
