# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0005_remove_document_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myaccount.MyUser'),
        ),
    ]
