# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-26 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0009_auto_20160721_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(null=True, unique=True),
        ),
    ]
